# Mandatory, application-private PDF Base14 resources. No network or TeX lookup.
include_guard(GLOBAL)

function(mengshee_read_pdf_base14_manifest source_root out_manifest)
    set(_root "${source_root}/external/pdf-base14-fonts")
    if(NOT EXISTS "${_root}/manifest.json")
        message(FATAL_ERROR "Missing mandatory PDF Base14 manifest: ${_root}/manifest.json")
    endif()
    file(READ "${_root}/manifest.json" _manifest)
    string(JSON _revision GET "${_manifest}" revision)
    if(NOT _revision STREQUAL "a84323421e94f484faca52dd9d027934eba42ab8")
        message(FATAL_ERROR "Unreviewed PDF Base14 font revision: ${_revision}")
    endif()
    string(JSON _count LENGTH "${_manifest}" fonts)
    if(NOT _count EQUAL 14)
        message(FATAL_ERROR "PDF Base14 manifest must contain exactly 14 fonts.")
    endif()
    set(${out_manifest} "${_manifest}" PARENT_SCOPE)
endfunction()

function(mengshee_require_pdf_font_hash path expected)
    if(NOT EXISTS "${path}" OR IS_DIRECTORY "${path}")
        message(FATAL_ERROR "Missing mandatory PDF font resource: ${path}")
    endif()
    file(SHA256 "${path}" _actual)
    if(NOT _actual STREQUAL expected)
        message(FATAL_ERROR "PDF font resource checksum mismatch: ${path}\nExpected ${expected}\nActual   ${_actual}")
    endif()
endfunction()

function(mengshee_validate_pdf_base14_sources source_root)
    mengshee_read_pdf_base14_manifest("${source_root}" _manifest)
    set(_root "${source_root}/external/pdf-base14-fonts")
    string(JSON _count LENGTH "${_manifest}" files)
    math(EXPR _last "${_count} - 1")
    foreach(_i RANGE 0 ${_last})
        string(JSON _relative MEMBER "${_manifest}" files ${_i})
        string(JSON _hash GET "${_manifest}" files "${_relative}")
        mengshee_require_pdf_font_hash("${_root}/${_relative}" "${_hash}")
    endforeach()
    if(NOT EXISTS "${_root}/NOTICE")
        message(FATAL_ERROR "Missing PDF Base14 attribution: ${_root}/NOTICE")
    endif()
endfunction()

function(mengshee_validate_pdf_base14_fonts source_root prefix)
    mengshee_read_pdf_base14_manifest("${source_root}" _manifest)
    set(_font_dir "${prefix}/share/fonts")
    foreach(_i RANGE 0 13)
        string(JSON _relative GET "${_manifest}" fonts ${_i} file)
        string(JSON _hash GET "${_manifest}" fonts ${_i} sha256)
        get_filename_component(_name "${_relative}" NAME)
        mengshee_require_pdf_font_hash("${_font_dir}/${_name}" "${_hash}")
    endforeach()
    set(_root "${source_root}/external/pdf-base14-fonts")
    foreach(_pair IN ITEMS "LICENSE|LICENSE.pdfium" "NOTICE|NOTICE.pdfium" "manifest.json|base14-manifest.json")
        string(REPLACE "|" ";" _parts "${_pair}")
        list(GET _parts 0 _source)
        list(GET _parts 1 _destination)
        file(SHA256 "${_root}/${_source}" _hash)
        mengshee_require_pdf_font_hash("${_font_dir}/${_destination}" "${_hash}")
    endforeach()
endfunction()

function(mengshee_deploy_pdf_base14_fonts source_root prefix)
    mengshee_validate_pdf_base14_sources("${source_root}")
    mengshee_read_pdf_base14_manifest("${source_root}" _manifest)
    set(_root "${source_root}/external/pdf-base14-fonts")
    set(_font_dir "${prefix}/share/fonts")
    file(MAKE_DIRECTORY "${_font_dir}")
    foreach(_i RANGE 0 13)
        string(JSON _relative GET "${_manifest}" fonts ${_i} file)
        get_filename_component(_name "${_relative}" NAME)
        file(COPY_FILE "${_root}/${_relative}" "${_font_dir}/${_name}" ONLY_IF_DIFFERENT)
    endforeach()
    file(COPY_FILE "${_root}/LICENSE" "${_font_dir}/LICENSE.pdfium" ONLY_IF_DIFFERENT)
    file(COPY_FILE "${_root}/NOTICE" "${_font_dir}/NOTICE.pdfium" ONLY_IF_DIFFERENT)
    file(COPY_FILE "${_root}/manifest.json" "${_font_dir}/base14-manifest.json" ONLY_IF_DIFFERENT)
    mengshee_validate_pdf_base14_fonts("${source_root}" "${prefix}")
endfunction()

function(mengshee_stage_pdf_base14_fonts source_root input_prefix stage_prefix)
    # Validate installed inputs rather than silently repair a corrupt install.
    mengshee_validate_pdf_base14_sources("${source_root}")
    mengshee_validate_pdf_base14_fonts("${source_root}" "${input_prefix}")
    mengshee_read_pdf_base14_manifest("${source_root}" _manifest)
    set(_names LICENSE.pdfium NOTICE.pdfium base14-manifest.json)
    foreach(_i RANGE 0 13)
        string(JSON _relative GET "${_manifest}" fonts ${_i} file)
        get_filename_component(_name "${_relative}" NAME)
        list(APPEND _names "${_name}")
    endforeach()
    file(MAKE_DIRECTORY "${stage_prefix}/share/fonts")
    foreach(_name IN LISTS _names)
        file(COPY_FILE "${input_prefix}/share/fonts/${_name}" "${stage_prefix}/share/fonts/${_name}" ONLY_IF_DIFFERENT)
    endforeach()
    mengshee_validate_pdf_base14_fonts("${source_root}" "${stage_prefix}")
endfunction()
